// WebSocket hub for overlay connections
const WebSocket = require('ws');
const pino = require('pino');

const logger = pino({ level: 'info' });

class WSHub {
  constructor() {
    this.connections = new Map(); // overlayKey -> Set of WebSocket connections
    this.wss = null;
  }

  // Initialize WebSocket server
  init(server) {
    this.wss = new WebSocket.Server({ 
      server,
      path: '/ws'
    });

    this.wss.on('connection', (ws, req) => {
      const url = new URL(req.url, `http://${req.headers.host}`);
      const overlayKey = url.searchParams.get('key');
      
      if (!overlayKey) {
        logger.warn('WebSocket connection without overlay key');
        ws.close(1008, 'Overlay key required');
        return;
      }

      logger.info(`New overlay connection for key: ${overlayKey}`);
      
      // Add to connections
      if (!this.connections.has(overlayKey)) {
        this.connections.set(overlayKey, new Set());
      }
      this.connections.get(overlayKey).add(ws);

      // Handle connection close
      ws.on('close', () => {
        logger.info(`Overlay connection closed for key: ${overlayKey}`);
        const connections = this.connections.get(overlayKey);
        if (connections) {
          connections.delete(ws);
          if (connections.size === 0) {
            this.connections.delete(overlayKey);
          }
        }
      });

      // Handle errors
      ws.on('error', (error) => {
        logger.error(`WebSocket error for overlay ${overlayKey}:`, error);
      });

      // Send welcome message
      ws.send(JSON.stringify({
        type: 'connection.established',
        overlayKey: overlayKey,
        timestamp: new Date().toISOString()
      }));
    });

    logger.info('WebSocket hub initialized');
  }

  // Broadcast message to all connections for a streamer
  broadcastToStreamer(streamerId, message) {
    // Find overlay key for streamer
    const store = require('../store');
    let overlayKey = null;
    
    for (const [id, streamer] of store.streamers) {
      if (id === streamerId) {
        overlayKey = streamer.overlayKey;
        break;
      }
    }

    if (!overlayKey) {
      logger.error(`No overlay key found for streamer ${streamerId}`);
      return;
    }

    this.broadcastToOverlay(overlayKey, message);
  }

  // Broadcast message to all connections for an overlay key
  broadcastToOverlay(overlayKey, message) {
    const connections = this.connections.get(overlayKey);
    if (!connections || connections.size === 0) {
      logger.warn(`No connections found for overlay key: ${overlayKey}`);
      return;
    }

    const messageStr = JSON.stringify(message);
    let sentCount = 0;

    for (const ws of connections) {
      if (ws.readyState === WebSocket.OPEN) {
        try {
          ws.send(messageStr);
          sentCount++;
        } catch (error) {
          logger.error('Error sending WebSocket message:', error);
        }
      }
    }

    logger.info(`Broadcasted message to ${sentCount} connections for overlay ${overlayKey}`);
  }

  // Send test reaction (for debugging)
  sendTestReaction(overlayKey) {
    const testMessage = {
      type: 'reaction.new',
      text: 'This is a test reaction! 🔥',
      audioUrl: null,
      style: 'support',
      tier: 'BASIC',
      orderId: 'test-' + Date.now()
    };

    this.broadcastToOverlay(overlayKey, testMessage);
  }

  // Generate and send emotional task
  async sendEmotionalTask(overlayKey, mode = 'funny', tone = 'playful') {
    try {
      // Generate simple emotional prompt
      const emotionalPrompt = this.generateSimpleEmotionalPrompt(mode, tone);
      logger.info(`Generated emotional prompt for ${overlayKey}: "${emotionalPrompt.text}"`);

      // Send to WebSocket clients (TTS will be handled by client)
      const taskMessage = {
        type: 'task',
        text: emotionalPrompt.text,
        voiceUrl: null, // Will be generated by client
        mode: mode,
        tone: tone,
        updatedAt: Date.now()
      };

      this.broadcastToOverlay(overlayKey, taskMessage);
      logger.info(`Emotional task sent to overlay ${overlayKey}`);

    } catch (error) {
      logger.error(`Error generating emotional task for ${overlayKey}:`, error);
      
      // Send error message
      this.broadcastToOverlay(overlayKey, {
        type: 'error',
        message: 'Failed to generate task'
      });
    }
  }

  // Generate simple emotional prompt
  generateSimpleEmotionalPrompt(mode, tone) {
    const templates = {
      funny: [
        "Слушай, друг! Расскажи анекдот прямо сейчас! Это будет невероятно! 😄",
        "Ого, зритель! Покажи фокус и пусть все увидят твою крутость! 😊",
        "Хей, приятель! Расскажи шутку и развлекай зрителей! 😄",
        "Эй, товарищ! Покажи танец и пусть все засмеются! 😊",
        "Слушай, человек! Расскажи историю и будь звездой! 😄"
      ],
      serious: [
        "Внимание, товарищ. Объясни тему немедленно. 😐",
        "Слушай, человек. Расскажи факт - это важно. 😐",
        "Внимание, зритель. Объясни концепцию прямо сейчас. 😐",
        "Слушай, участник. Расскажи о событии - это критично. 😐",
        "Внимание, посетитель. Объясни процесс немедленно. 😐"
      ],
      chill: [
        "Эй, приятель... Поделись мыслями когда будешь готов. 😌",
        "Привет, друг. Расскажи о дне в своем темпе. 😌",
        "Хей, товарищ... Поделись настроением когда захочешь. 😌",
        "Слушай, человек. Расскажи о планах расслабленно. 😌",
        "Привет, зритель... Поделись впечатлениями спокойно. 😌"
      ],
      street: [
        "Йо, чувак! Покажи свой стиль и пусть все знают! 😎",
        "Эй, братан! Расскажи о жизни и докажи свою крутость! 😎",
        "Слушай, чел! Покажи свой характер и пусть все видят! 😎",
        "Йо, человек! Расскажи о планах и покажи свою мощь! 😎",
        "Эй, товарищ! Покажи свой дух и докажи свою силу! 😎"
      ]
    };

    const modeTemplates = templates[mode] || templates.funny;
    const text = modeTemplates[Math.floor(Math.random() * modeTemplates.length)];

    return {
      text,
      voice: 'alloy',
      emotion: 'excited',
      style: 'dramatic',
      speed: 1.0
    };
  }

  // Get connection stats
  getStats() {
    const stats = {
      totalOverlays: this.connections.size,
      totalConnections: 0,
      overlays: {}
    };

    for (const [overlayKey, connections] of this.connections) {
      const count = connections.size;
      stats.totalConnections += count;
      stats.overlays[overlayKey] = count;
    }

    return stats;
  }
}

module.exports = new WSHub();


